---
# Source: member-cluster-rbac/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-healthz
  namespace: kube-system
---
# Source: member-cluster-rbac/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-healthz
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
---
# Source: member-cluster-rbac/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-healthz
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-healthz
subjects:
- kind: ServiceAccount
  name: cluster-healthz
  namespace: kube-system
---
# Source: member-cluster-rbac/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-healthz
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
---
# Source: member-cluster-rbac/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-healthz
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-healthz
subjects:
- kind: ServiceAccount
  name: cluster-healthz
  namespace: kube-system
